### ISSUE TITLE
Keys not matching rows in table

### ISSUE THREAD

**Issue by hanielc** [OfficeDev/Project-Power-BI-Content-Packs#33]
Hi,

I just tried loading the data from into the Power BI dashboard and got the following error - The key didn't match any rows in the table.
This error was reported on the following tables:

- Roadmap
- Roadmap Row
- Roadmap item
- Roadmap Key Dates

Any suggestions on how to overcome this?

Thanks,
-Haniel

![PowerBI Errors](https://github.com/OfficeDev/Project-Power-BI-Templates/assets/13683479/582eaff4-6e3d-4aa6-848a-b08cc17f1643)

**Comment by hanielc** [comment]
> Hi,
> 
> I just tried loading the data from into the Power BI dashboard and got the following error - The key didn't match any rows in the table. This error was reported on the following tables:
> 
> * Roadmap
> * Roadmap Row
> * Roadmap item
> * Roadmap Key Dates
> 
> Any suggestions on how to overcome this?
> 
> Thanks, -Haniel
> 
> ![PowerBI Errors](https://user-images.githubusercontent.com/13683479/278506866-582eaff4-6e3d-4aa6-848a-b08cc17f1643.jpg)

I installed the latest version of the Power BI dashboard and it works.  No further action needed.

**Comment by fellipetav** [comment]
That's not the only cause. Other root cause can be when you put other Environment URL wich is owned by your org but it's not the one where you belong as user (employee). It happened to me. The right URL can be found following the described in https://community.fabric.microsoft.com/t5/Desktop/Connecting-Power-BI-to-Project-for-the-Web/m-p/2862873#M986356.

It can help others like me.
